# sudo: false
language: python
cache: pip
sudo: required

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy-5.3.1

matrix:
  allow_failures:
  - python: pypy
  - python: pypy-5.3.1

before_install:
- sudo chown root:$USER /etc/fuse.conf
- pip install -U setuptools wheel

install:
- pip install .[dev,test]

script:
- green

after_script:
- codecov

notifications:
  email:
  - althonosdev@gmail.com
